-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVWGKJOZC/hJUqT2Y
/GBpXfBSjfen/GBTsWn8hAAEXJGgCgYIKoZIzj0DAQehRANCAAQoGXXpKjY+5PUR
+P1iJccjZhcp+Sq8PW+k3rxnMYZIWmabfLZsB52Qn+rM93EOeUAli11uKacULzKU
3yBgK4oY
-----END PRIVATE KEY-----